# The `service` block is the name of the service
service: FormUploaderService

frameworkVersion: '3'

# The `provider` block defines where your service will be deployed
custom:
  bucket: put-your-bucket-here
provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject" 
      Resource: 
        - "arn:aws:s3:::${self:custom.bucket}/*" 

# The `functions` block defines what code to deploy
functions:
  UploadImage:
    handler: awshandler.formUploadHandler
    # The `events` block defines how to trigger the awshandler.formUploadHandler code
    events:
      - http:
        path: upload
        method: post
        cors: true
    environment:
      Bucket: ${self:custom.bucket} 
resources:
  Resources:
    StorageBucket:
      Type: "AWS::S3::Bucket"
      Properties:
        BucketName: ${self:custom.bucket}
